# Generated by Django 4.2.3 on 2023-07-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
