# Generated by Django 4.2.3 on 2023-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_main', '0003_advertisements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='image',
            field=models.ImageField(default='', upload_to='advertisiments/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
